### ISSUE TITLE
Vimeo Thumbnail in Schema Preview / Prepare

### ISSUE THREAD

**Issue by hotlines-studio** [marco-land/sanity-plugin-vimeo-field#4]
Hi there,

Thank you for making this simple to install and easy to use plugin!

I'm able to add the Vimeo Title / Name to my schema preview like so:

```
preview: {
    select: {
      title: 'vimeo'
    },
    prepare: ({ title }) => {
      return {
        title: title.name
      }
    }
  }
```

I'm newer to Sanity, can't understand the preview / prepare for the media...

Is there any way to pass the Vimeo Thumbnail into the preview / prepare media to go with the title name?

**Comment by marco-land** [comment]
Hi,

the plugin stores a bunch of data from vimeo to your document, you can inspect the data with the sanity inspector, see below.

![CleanShot 2024-04-16 at 10 37 04@2x](https://github.com/marco-land/sanity-plugin-vimeo-field/assets/24410335/31f7478c-3e40-4601-8c94-28c0b1d47522).

Thumbnails are stored in `vimeo.pictures`. Since the thumbnails are just external image urls, you need to wrap them around an img tag (this would not be necessary for sanity assets). Here's a working example:

```js
preview: {
  select: {
    title: 'vimeo.name',
    picture: 'vimeo.pictures.sizes.[1].link',
  },
  prepare(selection) {
    const {title, picture} = selection
    return {
      title: title,
      media: <img src={picture} alt={title} />,
    }
  },
},
```

Please make sure to change your document to a `jsx` / `tsx` (and import `react`).

Preview should like this:
![CleanShot 2024-04-16 at 10 43 34@2x](https://github.com/marco-land/sanity-plugin-vimeo-field/assets/24410335/8dd08874-2e45-4299-bb88-d586d18b5704)

You can read more about this in the [sanity docs](https://www.sanity.io/docs/previews-list-views)

I hope this helps!

**Comment by hotlines-studio** [comment]
Sweet!! Thank you so much for this quick reply and perfect little demo. I saw the pictures data and all coming through, just wasn't clear about the react import and needing to turn my .js file into .jsx for the img tag.

Thanks again, this is great!

**Comment by hotlines-studio** [comment]
That thumbnail preview totally works now, thanks again!

Last question, hah, is there any way to hide the "Files" and "Play" fields, like with `hidden: true`? Since those are readonly, I was just thinking of not showing them so the client had less fields to look at. No big deal if this isn't possible.

<img width="687" alt="image" src="https://github.com/marco-land/sanity-plugin-vimeo-field/assets/20374795/882cb082-93f7-4ff3-a66d-9f85e4512f3c">

**Comment by marco-land** [comment]
Glad it works for you!

> Last question, hah, is there any way to hide the "Files" and "Play" fields, like with `hidden: true`? Since those are readonly, I was just thinking of not showing them so the client had less fields to look at. No big deal if this isn't possible.

At the moment this is not an option, but I might remove that in the next release and just display title + thumbnail.

**Comment by hotlines-studio** [comment]
Sounds good, thanks again!
